### ISSUE TITLE
Confusion about phpstan with Param

### ISSUE THREAD

**Issue by radonthetyrant** [php-static-analysis/rector-rule#1]
Hello, I am unsure if this is the right spot for the issue in this repository, but it concerns a phpstan analysis run after rector, with help of this extension, changed the phpdoc tags to attributes. The subsequent phpstan runs fail.

I have the following code of a Symfony Application:

```php

namespace Api\Infrastructure;

// uses...

class ReferenceExpansion
{
    // ...

    #[Param(documents: 'array<array-key, (array | BaseEntity | SerializableDto | Document)>')]
    #[Param(includes: 'array<string>')]
    #[Param(context: 'array<string, mixed>')]
    public function applyReferenceExpansions(iterable $documents, array $includes, array $context = []): array
    {
        //....
    }
}
```

I make a call to this function:
```php

        if (null === ($user = $this->entityManager->getRepository(User::class)->findOneBy($criteria))) {
            throw new NotFoundHttpException('User not found');
        }

        [$normalized] = $this->referenceExpansion->applyReferenceExpansions([$user], $query->getIncludes(), [AbstractNormalizer::GROUPS => ['user:admin', 'user:read']]);
```

`class User extends Api\Infrastructure\BaseEntity`

When i run phpstan, i see the error:

```
 ------ --------------------------------------------------------------------------------------------------------------- 
  Line   application/src/User/Handler/FindUserByIdStaffHandler.php                                                      
 ------ --------------------------------------------------------------------------------------------------------------- 
  62     Parameter #1 $documents of method                                                                              
         Api\Infrastructure\ReferenceExpansion::applyReferenceExpansions()                                         
         expects                                                                                                        
         iterable<array|Elastica\Document|Api\Infrastructure\BaseEntity|Api\Infrastructure\SerializableDto>,  
         array<int, Api\User\User> given.                                                                          
 ------ ---------------------------------------------------------------------------------------------------------------
```

My confusion stems from the fact, that the `array<int, Api\User\User>` with the `User` class extending the `Api\Infrastructure\BaseEntity` fulfills the requirement of it being an iterable of the base type.

Why do i see this error and what do i need to change?

**Comment by carlos-granados** [comment]
Sorry for the late reply, I hope you have been able to find the solution to this problem. If not, do you get the same error if you use annotations instead of this attribute? If you do, you probably need to post this question in PhpStan. If you do, let me know and I'll re-open the issue

**Comment by radonthetyrant** [comment]
> Sorry for the late reply, I hope you have been able to find the solution to this problem. If not, do you get the same error if you use annotations instead of this attribute? If you do, you probably need to post this question in PhpStan. If you do, let me know and I'll re-open the issue

No, this error only happens with the Attributes. The code as-is is passing phpstan when used with annotations.
